server:
  port: 7000
spring:
  datasource:
    url: jdbc:mysql://192.168.50.213:3306/gulimall_sms?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false&useAffectedRows=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: mysql@gisquest.com
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
